services:
  knots:
    build: ./knots
    restart: on-failure
    volumes:
      - knots_data:/home/bitcoin/.bitcoin
  miner:
    build: ./miner
    restart: on-failure
    volumes:
      - knots_data:/home/bitcoin/.bitcoin

  electrs:
    build: ./electrs
    restart: on-failure
    volumes:
      - electrs_data:/data

  mariadb:
    build: ./mariadb
    restart: on-failure
    volumes:
      - mariadb_data:/var/lib/mysql

  mongo:
    build: ./mongo
    restart: on-failure
    volumes:
      - mongo_data:/data/db

  mempool-api:
    build: ./mempool-api
    environment:
      - CORE_RPC_HOST=knots
      - CORE_RPC_PASSWORD=easepay
      - CORE_RPC_PORT=38332
      - CORE_RPC_USERNAME=easepay
      - DATABASE_DATABASE=mempool
      - DATABASE_ENABLED=true
      - DATABASE_HOST=mariadb
      - DATABASE_PASSWORD=mempool
      - DATABASE_USERNAME=mempool
      - ELECTRUM_HOST=electrs
      - ELECTRUM_PORT=60601
      - ELECTRUM_TLS_ENABLED=false
      - MEMPOOL_BACKEND=electrum
      - MEMPOOL_NETWORK=signet
      - STATISTICS_ENABLED=false
    restart: unless-stopped

  mempool-web:
    build: ./mempool-web
    environment:
      - BACKEND_MAINNET_HTTP_HOST=mempool-api
      - FRONTEND_HTTP_PORT=8080
      - MEMPOOL_NETWORK=signet
    ports:
      - 127.0.0.1:8080:8080
    restart: on-failure

  faucet:
    build: ./faucet
    environment:
      - BITCOIND_HOST=knots
      - BITCOIND_USER=easepay
      - BITCOIND_PASS=easepay
      - MONGODB_HOST=mongo
    ports:
      - 127.0.0.1:8123:8123
    restart: on-failure

volumes:
  electrs_data:
  knots_data:
  mariadb_data:
  mongo_data:
